<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R_onceOffWithdrawal0.amount</name>
   <tag></tag>
   <elementGuidId>e177a106-e24d-480c-8ade-f6cc68e47787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onceOffWithdrawal[0].amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Amount&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af688e6f-bffd-4ea5-a28b-04ac9fd22a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onceOffWithdrawal[0].amount</value>
      <webElementGuid>b186be80-cae2-4c54-b9fd-ee9f24c5923f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>872b9514-236a-441e-9558-a3b0ccde547f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onceOffWithdrawal[0].amount</value>
      <webElementGuid>80a47e31-03be-4aaa-a08c-64c894d9c16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onceOffWithdrawal[0].amount&quot;)</value>
      <webElementGuid>92890dfc-5191-4e7f-86c8-a65a0edd8509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onceOffWithdrawal[0].amount']</value>
      <webElementGuid>f1edb7c3-08ba-48a6-8eaa-8c549feec222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/form/div[2]/div[2]/div/div/div/div[2]/div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>af58c278-8a6b-48c5-80ad-d90d2ae0621b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/input</value>
      <webElementGuid>00cc6b86-5755-44d0-8dcb-bf7cfcdc29f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'onceOffWithdrawal[0].amount' and @type = 'number' and @name = 'onceOffWithdrawal[0].amount']</value>
      <webElementGuid>92f8d8fd-d4be-41b7-85e4-3228c905d867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
