<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pages is taking to lon</name>
   <tag></tag>
   <elementGuidId>b7bb1e45-e7d7-475f-b604-f04b5bfd94ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;If the page contains an error message please provide it with the page address.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>572bcca7-01de-40f0-a346-5654328d067e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>974855b1-de97-4d14-9efb-d77f53778184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>18e51ae3-23ea-4a24-9433-85b738dfcef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>4376d4f8-5ecf-48d1-a0c2-2b2ee4ce9d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>If the page contains an error message please provide it with the page address.</value>
      <webElementGuid>4636fc85-0d87-46c2-b34a-fe2fe53cb52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pages is taking to lon</value>
      <webElementGuid>e488a489-9a56-4ad8-b63e-863e38ec6736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comments&quot;)</value>
      <webElementGuid>aec1a07b-6d1c-43ec-a0d9-c5fc406f92b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comments']</value>
      <webElementGuid>426fc13b-a4f4-4340-9fad-213e2975958c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/main/div[2]/section/section/form/div[5]/div/div/textarea</value>
      <webElementGuid>d2b205ce-1311-4cdc-a455-f9dbbaa1e99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::textarea[1]</value>
      <webElementGuid>445c2897-f073-449f-8345-c35af18a1245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::textarea[1]</value>
      <webElementGuid>1b2a25e0-6330-485c-b9bd-742c4dfcebce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Message'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ddefcd05-89c2-4f71-99ca-aa0ffbf6cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::textarea[1]</value>
      <webElementGuid>15ebebe4-257e-4524-bd12-bfc4cd73e237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pages is taking to lon']/parent::*</value>
      <webElementGuid>c1ffa669-9892-401d-9dbc-a920dd892968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3db6279d-86a5-4e3d-ba4f-3bf6bbdde5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comments' and @type = 'textarea' and @id = 'comments' and @placeholder = 'If the page contains an error message please provide it with the page address.' and (text() = 'pages is taking to lon' or . = 'pages is taking to lon')]</value>
      <webElementGuid>4613e5fd-aafd-4cac-889f-faad22040fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
