<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pages is taking to_1</name>
   <tag></tag>
   <elementGuidId>5e4e5a25-925f-49da-a050-c512586295e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;If the page contains an error message please provide it with the page address.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e3bbec6a-b6f2-4107-8dae-1e3b9a4b7ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>33b6e4c7-9484-49d0-bdc8-ec594373e1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>74c9f377-4499-4bd5-bbba-a112c2c8c4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comments</value>
      <webElementGuid>ad2e6877-f089-45f5-85b2-d20a1c0df66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>If the page contains an error message please provide it with the page address.</value>
      <webElementGuid>d15b1f9a-96fa-434a-bd11-f88ffc4d7d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pages is taking to </value>
      <webElementGuid>5af55074-7262-4140-80f5-62da7f4bead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comments&quot;)</value>
      <webElementGuid>e00911b8-eca7-4801-9ff6-34416ca75eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comments']</value>
      <webElementGuid>40af9ccd-3c51-4dc9-8c1f-1a0e8dc76169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/main/div[2]/section/section/form/div[5]/div/div/textarea</value>
      <webElementGuid>d5f47a90-d610-4bb2-8e63-15a5fb6aaa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::textarea[1]</value>
      <webElementGuid>895f2b25-f7a9-4366-95a9-ed30f43816ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::textarea[1]</value>
      <webElementGuid>75e8a6b2-5cfd-4b2c-897f-ad8d2d0241bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Message'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ef7859ab-d7d4-421b-8bbf-99c95a99fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f188fb6c-ae37-4a4a-85b0-2b2e3377db98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pages is taking to']/parent::*</value>
      <webElementGuid>832cbe6c-9d64-4884-aec3-9cbb1bbcd0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b9765780-7fe5-40c0-841f-49014af811b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comments' and @type = 'textarea' and @id = 'comments' and @placeholder = 'If the page contains an error message please provide it with the page address.' and (text() = 'pages is taking to ' or . = 'pages is taking to ')]</value>
      <webElementGuid>1f0fd069-acad-42e9-8a85-179a4d1b0f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
