<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fund</name>
   <tag></tag>
   <elementGuidId>c12f8921-61cc-4748-9403-16c85c07fa2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.InvestmentActionRow_label__15guG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/div/div[2]/div/div/div/h5/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Fund Prescient Money Market Fund - A&quot;i] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a4d1f41-7eb2-456b-9a82-83b7dfae94c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InvestmentActionRow_label__15guG</value>
      <webElementGuid>bc0765b2-3b06-4f95-bf63-d2bf0d731cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fund</value>
      <webElementGuid>ecbe397f-1b67-4103-822d-9d0036d7586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40 gapped-32&quot;]/div[@class=&quot;text-black gapped-40 pb-40&quot;]/div[@class=&quot;gapped-40&quot;]/div[@class=&quot;gapped-12&quot;]/div[@class=&quot;gapped-12&quot;]/div[@class=&quot;gapped-16&quot;]/div[@class=&quot;InvestmentActionRow_investmentactionrow__gNScM InvestmentActionRow_forcedlabels__Lv3Il&quot;]/div[@class=&quot;InvestmentActionRow_instructionrow__VdGUJ&quot;]/h5[1]/span[@class=&quot;InvestmentActionRow_label__15guG&quot;]</value>
      <webElementGuid>8b4587e9-ad31-406c-a7f0-2fcde56c4738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/div/div[2]/div/div/div/h5/span</value>
      <webElementGuid>f41a246b-4d3a-4727-9332-828359962059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vested'])[1]/following::span[1]</value>
      <webElementGuid>af5da060-502f-46b4-bca0-ed8a120059aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% of Portfolio'])[1]/preceding::span[1]</value>
      <webElementGuid>68fa3f2b-d1ed-40b5-9e16-589c6a6dc6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Units'])[1]/preceding::span[3]</value>
      <webElementGuid>c7e1227a-4bd7-42cf-b81e-4021d19b659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fund']/parent::*</value>
      <webElementGuid>b18607dc-7b66-4517-9482-6236b887f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/span</value>
      <webElementGuid>4370e45e-243c-459c-b84e-a587c57f6df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Fund' or . = 'Fund')]</value>
      <webElementGuid>f34e77c9-13a1-400b-882f-f63612282bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
