<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Allow</name>
   <tag></tag>
   <elementGuidId>4d47660e-37e1-4f49-a627-8bb203b62d08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button_button__jYOrq.Button_primary__ZJqjB.Button_small__TnQmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Allow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58888f60-da61-4c05-8fed-ca26619bfa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_button__jYOrq Button_primary__ZJqjB Button_small__TnQmo</value>
      <webElementGuid>dd284b79-46bb-4e4b-ad2f-6378c2b4d2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c7be753-a663-48d8-bbe3-9601561a4a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>acceptCookie()</value>
      <webElementGuid>8f58dc93-f645-4bf0-a7e8-187e2f9a1acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow</value>
      <webElementGuid>b7aca10c-a9d8-4ab9-b521-5c42434511ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;LoginTemplate_logintemplate__VHwmT&quot;]/div[@class=&quot;LoginTemplate_loginform__1IkkF pb-40&quot;]/div[1]/div[@class=&quot;px-20 md:px-40 lg:px-xl pt-0&quot;]/footer[@class=&quot;cookie-policy p-16 flex items-center justify-between mt-auto bg-primaryPrimaryBlue&quot;]/div[@class=&quot;ButtonGroup_buttongroup__dCVlI flex ml-20 gap-8&quot;]/button[@class=&quot;Button_button__jYOrq Button_primary__ZJqjB Button_small__TnQmo&quot;]</value>
      <webElementGuid>2226b01c-eb88-41a6-a933-50e45f872cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>86077dc5-adf8-40ab-bcad-1fa9507969f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/following::button[1]</value>
      <webElementGuid>1a0d3874-8b5a-4eea-a9ac-582c97da4d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[2]</value>
      <webElementGuid>c911f197-171e-4537-a892-7f0938d7430d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAILORED COST-EFFECTIVE INVESTMENT PRODUCTS'])[1]/preceding::button[1]</value>
      <webElementGuid>65e38882-9ed5-4570-b1a8-b81be944c81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVEST NOW'])[1]/preceding::button[1]</value>
      <webElementGuid>6339da05-b380-4b5b-89ae-13cf717bee62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow']/parent::*</value>
      <webElementGuid>8d43f945-2810-4983-81e8-611b1e8b55b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e5ba886a-4447-43ad-be9d-38acec0a7307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Allow' or . = 'Allow')]</value>
      <webElementGuid>e0a4529e-6d4e-4828-a648-0d2a67ebb445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
