<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>658627d3-8b0e-40a0-9cef-47361edf4c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/nav/div/div[2]/div/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MenuItem_menuitem__YHK_7.type-14 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43d4688d-98aa-404a-9d59-4d05254559db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>ef6d6a2f-6c97-4a4a-a4ae-12d6016dde6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>61c8b963-306b-491e-9e98-31bd745afd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/nav[@class=&quot;bg-companyAccent p-20 pr-48 md:p-0 flex flex-col justify-center 
         md:justify-between md:pb-[120px] top-0 sticky md:relative Page_nav__gVIjV&quot;]/div[1]/div[@class=&quot;Page_menuWrapper__wJebB&quot;]/div[@class=&quot;overflow-hidden Menu_menu__Heunw Page_menu__Doh5I&quot;]/li[@class=&quot;MenuItem_menuitem__YHK_7 type-14&quot;]/a[1]</value>
      <webElementGuid>992cfefa-098c-4b29-9f8f-f8f35e2efbbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/nav/div/div[2]/div/li/a</value>
      <webElementGuid>87e2cb3c-69bb-452f-8da3-936ff8de191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>5c057465-26d8-4ada-b74b-0d2133fc681f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N TestDI'])[1]/following::a[2]</value>
      <webElementGuid>f7e72363-2dd8-4e24-8da6-641703bcaf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NML TestDI'])[1]/following::a[2]</value>
      <webElementGuid>94aae779-49d5-4f56-b300-596bc461bc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Investments'])[1]/preceding::a[1]</value>
      <webElementGuid>4d21c78e-7f00-488e-b901-01e1fe3f716d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Trust'])[1]/preceding::a[1]</value>
      <webElementGuid>af1a7449-234a-4d14-b15c-815f8c47a19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>657969db-981f-4318-8882-590938f17332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[2]</value>
      <webElementGuid>ef4b1d4d-e11b-4ba0-a7f1-9b4f1904b8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>d0184166-79c2-4e74-a383-3cfaaec7430a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>357d2f59-d0c1-4a6b-b354-f7ea0d488c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
