<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Factsheets</name>
   <tag></tag>
   <elementGuidId>e76c693b-1e6b-4c5d-9c7f-9fbbbb6d1f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/section/section/div/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.type-16.font-medium.text-neutralsDark100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h2 >> internal:has-text=&quot;Factsheets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c1ba3655-6754-424d-9086-7ea5a9be519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>type-16 font-medium text-neutralsDark100</value>
      <webElementGuid>f6080e9a-a7d1-42be-938b-c9c300ae669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Factsheets</value>
      <webElementGuid>828b1630-d4ce-469f-a32d-f32ca8cea41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40&quot;]/div[@class=&quot;text-black gapped-40 pb-40&quot;]/section[@class=&quot;grid gap-40 md:grid-cols-3&quot;]/section[@class=&quot;col-span-3 sm:col-span-2 gapped-16 type-14&quot;]/div[1]/div[@class=&quot;stick&quot;]/div[@class=&quot;bg-neutralsDark10 flex justify-between items-center p-20 cursor-pointer&quot;]/div[@class=&quot;flex justify-between items-center gap-20 stick&quot;]/h2[@class=&quot;type-16 font-medium text-neutralsDark100&quot;]</value>
      <webElementGuid>b9cf80be-ac32-46b9-ae5c-8d9a4b8312b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/section/section/div/div/div/div/h2</value>
      <webElementGuid>3d3dbda2-be1a-492c-aabf-11ee75bc9ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Factsheets'])[2]/following::h2[1]</value>
      <webElementGuid>e5e7b043-dd41-44ac-a8d4-2393bb1c353b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brochures'])[1]/following::h2[1]</value>
      <webElementGuid>54118aff-ec4f-48ef-823c-b0a47fbf9ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescient Collective Investment Schemes'])[1]/preceding::h2[1]</value>
      <webElementGuid>d1d298e6-1541-4e38-b499-df03f3218bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::h2[2]</value>
      <webElementGuid>a52530ab-5934-4de0-b59a-d95d8bdcf580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>8e3a1207-ea8f-4b53-812d-3e0c368d66a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Factsheets' or . = 'Factsheets')]</value>
      <webElementGuid>5a7d1fa1-fb25-4ca2-b3b4-06b2a7d068b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
