<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Prescient Balanced Fund - B3</name>
   <tag></tag>
   <elementGuidId>9ce15b00-6cc6-4f19-b47a-95fc6a58246a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Prescient Balanced Fund - B3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02b3ceec-43ef-45a0-a23b-45394520467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>24b377a5-bb15-4826-8940-f0bc5ddb8298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d36704f-11db-4833-95d8-5484e1e65cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-3-option-0</value>
      <webElementGuid>0e1a02fb-c02d-4eb7-b545-520bc054fa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3d3ab32b-0c81-4b6a-aa47-14f729e69831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e46f0e62-f339-4cc7-afc2-229cf74f442d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44563fba-f932-4af3-bc9f-225ac56c17da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prescient Balanced Fund - B3</value>
      <webElementGuid>bc2d6747-863e-46ba-a58f-10311f97f56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-option-0&quot;)</value>
      <webElementGuid>f03484f8-a9f0-4356-be62-046c5159562b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-option-0']</value>
      <webElementGuid>87a11421-64ed-4bf3-8964-4db1391f5cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-listbox']/div</value>
      <webElementGuid>68f4b9b8-3886-4674-8563-54a1cd293acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Fund to Switch from'])[1]/following::div[11]</value>
      <webElementGuid>75aee125-8a39-47bf-a7bf-7b9a8bf85fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch From'])[1]/following::div[16]</value>
      <webElementGuid>5f124cf5-187a-4936-8e6e-5274c205a502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescient Defensive Fund - A2'])[2]/preceding::div[1]</value>
      <webElementGuid>e6b1f3d9-347f-49ad-9b3a-46ee558fc623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescient Positive Return QuantPlus Fund - A1'])[2]/preceding::div[2]</value>
      <webElementGuid>4a1c4b4a-358b-43f1-b310-6374c73c614f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>5518a951-2da3-4cc8-9788-2bac483a5c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-3-option-0' and (text() = 'Prescient Balanced Fund - B3' or . = 'Prescient Balanced Fund - B3')]</value>
      <webElementGuid>8d081b2e-d74f-4c1d-967d-9a6032ef42d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
