<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Allocation</name>
   <tag></tag>
   <elementGuidId>2a3c9be6-8a1c-4eea-95b2-a76d23e6c162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Allocation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>74575f17-162f-4bbd-b3c6-eeea92b3c5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:absolute lg:-top-40 text-12 text-neutralsDark70</value>
      <webElementGuid>8d9fc624-a407-4f35-ae3a-ef36f45c0c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allocation</value>
      <webElementGuid>b57918f9-9967-419f-8ba3-9b0266898d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40&quot;]/div[@class=&quot;text-black gapped-40 pb-40&quot;]/div[@class=&quot;gapped-12&quot;]/div[1]/div[@class=&quot;gapped-40&quot;]/div[1]/div[@class=&quot;gapped-20&quot;]/div[@class=&quot;p-20 border border-neutralsDark20 grid grid-cols-4 lg:grid-cols-8 gap-12&quot;]/div[@class=&quot;relative col-span-2 lg:col-span-1 flex flex-col gap-4&quot;]/span[@class=&quot;lg:absolute lg:-top-40 text-12 text-neutralsDark70&quot;]</value>
      <webElementGuid>20047099-0b00-4cc5-b6b5-7b658f39d137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[4]/span</value>
      <webElementGuid>497783e0-4237-42c4-b825-c402ea23cfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R 300,00'])[1]/following::span[1]</value>
      <webElementGuid>05e40b6c-b6ef-4d83-a60f-61108858cb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::span[2]</value>
      <webElementGuid>9916157e-ef70-4813-b9aa-8e1ef4c8a3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fund Name'])[1]/preceding::span[3]</value>
      <webElementGuid>cb0ef854-332d-4698-a842-71dd1a136155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorised'])[1]/preceding::span[6]</value>
      <webElementGuid>8d638249-ad35-4450-8cbd-af0e12d8f883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allocation']/parent::*</value>
      <webElementGuid>7f24937f-59b7-476a-b3f4-72b4602b5e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>f61a09b9-7573-4535-8559-ca64a8732a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Allocation' or . = 'Allocation')]</value>
      <webElementGuid>4ff4cda2-d6bb-4e43-bb3e-51792f66e6eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
