<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transact</name>
   <tag></tag>
   <elementGuidId>e2c88437-4281-42ba-94da-dedb01820e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/nav/div/div[2]/div/li[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Transact&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>477f895b-aef7-4b6d-87e1-79f6db7bc44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MenuItem_togglespan__FZ1Px</value>
      <webElementGuid>8ca846b5-2b4a-4bbf-b435-5652eabe21cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transact</value>
      <webElementGuid>178a7a66-d63e-4b3a-ac75-c3c740f174f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/nav[@class=&quot;bg-companyAccent p-20 pr-48 md:p-0 flex flex-col justify-center 
         md:justify-between md:pb-[120px] top-0 sticky md:relative Page_nav__gVIjV&quot;]/div[1]/div[@class=&quot;Page_menuWrapper__wJebB&quot;]/div[@class=&quot;overflow-hidden Menu_menu__Heunw Page_menu__Doh5I&quot;]/li[@class=&quot;MenuItem_menuitem__YHK_7 type-14&quot;]/span[@class=&quot;MenuItem_togglespan__FZ1Px&quot;]</value>
      <webElementGuid>ad683d10-96c3-4f3f-b61a-a067d8f1b925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/nav/div/div[2]/div/li[4]/span</value>
      <webElementGuid>8104aa03-83cc-476b-b29d-f551da098e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Instructions'])[1]/following::span[1]</value>
      <webElementGuid>fe53e7d5-d5a7-4996-8609-800bee30b649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Investments'])[1]/following::span[2]</value>
      <webElementGuid>6cb348c3-60cc-4c20-b092-ee4e35060185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linked Investments'])[1]/preceding::span[2]</value>
      <webElementGuid>ccaa2155-7f2f-4700-998e-7b2bc4d8c405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Centre'])[1]/preceding::span[3]</value>
      <webElementGuid>af3aecd8-fa6a-4d65-a7fc-d9e8e53ebdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transact']/parent::*</value>
      <webElementGuid>173ea32c-719a-42a0-977c-6e73d226c554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>40820c1f-efdb-4f96-a8fe-b1c7cd2559fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transact' or . = 'Transact')]</value>
      <webElementGuid>0f8cb865-077e-491b-a61b-7df2f03ef948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transact Now'])[1]/preceding::span[2]</value>
      <webElementGuid>4b7eba7b-bc7a-42d6-b75e-fd635097dd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Transactions'])[1]/preceding::span[2]</value>
      <webElementGuid>6383d077-a840-4e2b-8269-a7af574650f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
