<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contribute</name>
   <tag></tag>
   <elementGuidId>8ece12a2-543b-4349-b767-e1f956d8171e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/main/section[2]/article/a[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Contribute&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>614e3dca-fc54-4161-8c80-7ca734e9a3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-textButton</value>
      <webElementGuid>3d970c1e-76a4-47bf-9acf-5d4ba0adbff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contribute</value>
      <webElementGuid>2ba16ee6-1efe-43e8-8563-d5ee7c48877b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/main[@class=&quot;px-24 md:px-40&quot;]/section[@class=&quot;mt-4&quot;]/article[@class=&quot;DirectInvestorDashboard_dashboardlaunchpad__CvTKN col-span-2 lg:col-span-3 grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 items-center gap-20&quot;]/a[2]/span[@class=&quot;LaunchPadBlock_large__IJBjE flex-col bg-neutralsDark10 border-neutralsLightWhite border-1.5 hover:border-neutralsDark20 transition px-16 flex gap-12 items-center justify-center text-center LaunchPadBlock_launchpadblock__YHmyz&quot;]/span[@class=&quot;text-textButton&quot;]</value>
      <webElementGuid>f4f4e71b-aa5d-4e95-9a9a-fa18d6f9fc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/main/section[2]/article/a[2]/span/span</value>
      <webElementGuid>c5ccb3b1-daa7-4928-b7e4-1daa4858618e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Investment'])[1]/following::span[2]</value>
      <webElementGuid>d00d5305-ceaa-4c9e-8a7d-3371f6f8f21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What would you like to do next?'])[1]/following::span[4]</value>
      <webElementGuid>adc31446-bcfb-4643-9b9f-0563d74c9fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch'])[1]/preceding::span[1]</value>
      <webElementGuid>e6a530ee-adcf-49e8-a2f4-b22de4303f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw'])[1]/preceding::span[3]</value>
      <webElementGuid>bcb29821-cd51-4556-8150-bd2637e94580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contribute']/parent::*</value>
      <webElementGuid>823da3e2-0539-42b5-82be-40a6a011227a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/span</value>
      <webElementGuid>7ae090ce-f92e-4f65-84f0-f529ebc846f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contribute' or . = 'Contribute')]</value>
      <webElementGuid>f536c670-86a0-4b52-9e6f-884ddb6af955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/main/section[2]/article/a[2]/span</value>
      <webElementGuid>e8f41653-5b08-4759-a547-bee595f43c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Investment'])[1]/following::span[1]</value>
      <webElementGuid>f7538f11-c2e2-45d0-a03f-41ae16a0351a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What would you like to do next?'])[1]/following::span[3]</value>
      <webElementGuid>fedd09af-8da9-4449-a207-12df928c081c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch'])[1]/preceding::span[2]</value>
      <webElementGuid>0feadba9-ee4e-4490-930f-10df8f05204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>bdf638b6-b4ed-4bc3-8797-601213186956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
