<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Download</name>
   <tag></tag>
   <elementGuidId>e3c40696-ceb9-4a09-a59e-889fe2416a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Button_children__c7wUH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/form/div[2]/div[3]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Download&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10d17284-06f4-43cf-9431-f1024b76d21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_children__c7wUH</value>
      <webElementGuid>bf35f314-039a-4bf5-b645-862d9f755b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>074972eb-b667-46ce-aa08-d9d07190cddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40 gapped-32&quot;]/div[@class=&quot;text-black gapped-40 pb-40&quot;]/div[@class=&quot;gapped-40&quot;]/form[1]/div[@class=&quot;max-w-4xl w-full flex gap-12 flex-col sm:flex-row md:flex-col lg:flex-row&quot;]/div[@class=&quot;inline-block flex-1&quot;]/button[@class=&quot;Button_button__x6lHc Button_primary__a8YrV RequestFileDownload_requestfiledownload__89s5_&quot;]/div[@class=&quot;Button_children__c7wUH&quot;]</value>
      <webElementGuid>ea22df25-8b1c-4888-bc4a-adf0e2154255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div[2]/div/form/div[2]/div[3]/button/div</value>
      <webElementGuid>0d633ef2-11ce-4963-8e36-cc150cb87be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::div[5]</value>
      <webElementGuid>c8201859-6c33-4f7e-97a0-e304b984cd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a report'])[1]/following::div[20]</value>
      <webElementGuid>c661cc81-6b11-4762-b65d-de6d73fa1c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLUF00003'])[2]/preceding::div[3]</value>
      <webElementGuid>c017cc7f-a4e9-4ab9-80a5-d8ca62dcecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>f4dd3b15-011e-418f-905b-519593779821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>807e18c1-81b9-4e24-9c6c-1ad866003464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>6c6512c0-1785-4367-a8d7-099c8c411164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
