<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_infoprescient.co.za</name>
   <tag></tag>
   <elementGuidId>9b6df7d3-65d1-429f-831f-57e638362cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div/div[2]/div/div[2]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;info@prescient.co.za&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa1dd1d2-ca9a-4016-aa8d-12b4793c4354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:underline</value>
      <webElementGuid>2f0ad6d1-0011-4d63-bbee-9ba5d0a99107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:info@prescient.co.za</value>
      <webElementGuid>3be10d61-83c6-493f-8e0c-021845d8f1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>info@prescient.co.za</value>
      <webElementGuid>c34c3a9f-1216-44e0-89c7-8fa10bbc9f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40 pb-xl&quot;]/div[@class=&quot;grid grid-cols-3 gap-40 pt-20&quot;]/div[@class=&quot;col-span-3 sm:col-span-2 gapped-28&quot;]/div[1]/div[@class=&quot;p-20 md:p-24 border border-neutralsDark10 grid grid-cols-2 lg:grid-cols-3 gap-32&quot;]/div[@class=&quot;col-span-3 lg:col-span-1&quot;]/ul[@class=&quot;gapped-4&quot;]/li[@class=&quot;pb-20 type-14 text-neutralsDark60&quot;]/a[@class=&quot;hover:underline&quot;]</value>
      <webElementGuid>c34671ab-20d0-4aee-85b2-e45d8228bb20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/div/div[2]/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>53deaf75-aee4-4868-82aa-f07e7b26b1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'info@prescient.co.za')]</value>
      <webElementGuid>74f6b9fd-6d79-436e-b292-86b52e494e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Details'])[1]/following::a[2]</value>
      <webElementGuid>ecc891e2-d24a-4065-b110-f4628ca5e81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cape Town Office'])[1]/following::a[2]</value>
      <webElementGuid>8471974f-3ae9-454a-aad4-026806abb1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax 021 7000 3700'])[1]/preceding::a[1]</value>
      <webElementGuid>a9c98eee-6643-4727-a653-9bbd5439fae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='info@prescient.co.za']/parent::*</value>
      <webElementGuid>aecee330-151c-467a-b892-f0faa7bdab91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:info@prescient.co.za')]</value>
      <webElementGuid>6ff922e1-fdbd-4bc6-8407-230ad065a348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]/a</value>
      <webElementGuid>09434e57-6ab5-4456-8fc5-15a3565a1a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:info@prescient.co.za' and (text() = 'info@prescient.co.za' or . = 'info@prescient.co.za')]</value>
      <webElementGuid>cad6fb8e-462b-4680-bc27-4b87458c8f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
