<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Back to Dashboard</name>
   <tag></tag>
   <elementGuidId>69802a79-2a08-4b17-9be6-64bc63540546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div/div/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Button_children__c7wUH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Back to Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f345011-6e93-4100-b951-2ac68d2c4a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_children__c7wUH</value>
      <webElementGuid>edf7e20f-1224-45d6-9775-48ac62ca8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Dashboard</value>
      <webElementGuid>d908b9e7-b0fa-4f99-9a4c-e4ddda00cdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40&quot;]/div[@class=&quot;text-center flex items-center justify-center flex-col gap-40 md:py-48 h-full max-w-xl mx-auto text-pretty&quot;]/div[@class=&quot;gapped-32&quot;]/div[@class=&quot;gapped-20 flex flex-col pt-40 mx-auto&quot;]/button[@class=&quot;Button_button__x6lHc Button_naked__nE_XJ&quot;]/div[@class=&quot;Button_children__c7wUH&quot;]</value>
      <webElementGuid>be51d12c-59ff-4f5d-9251-8599d613cc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div/div/div/div/button/div</value>
      <webElementGuid>4de16c7c-c098-4908-b6d8-8541389d081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::div[2]</value>
      <webElementGuid>97259258-c61e-42c3-880d-590ba3cd6adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::div[6]</value>
      <webElementGuid>e0e46a6e-660d-421a-b225-102c2d551d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::div[1]</value>
      <webElementGuid>127dc2fc-64fa-4e62-8af3-25eb5189cb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Notices'])[1]/preceding::div[1]</value>
      <webElementGuid>2bebc71e-1906-41b6-97a2-494142653a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to Dashboard']/parent::*</value>
      <webElementGuid>e779aac8-b7d1-4ba1-b59a-e4c14ff73301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>457db102-3eee-49c0-8352-2279ca8345da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Back to Dashboard' or . = 'Back to Dashboard')]</value>
      <webElementGuid>1898497d-9da2-427b-b5cf-7b658ff80b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
