<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Prescient</name>
   <tag></tag>
   <elementGuidId>5bd2b21a-05a2-4ce4-a0e2-ac5abeeb69e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/header/div/h1/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Welcome to Prescient&quot;i] >> internal:role=strong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>d3b08f3a-b4d3-4be5-9924-0a516c80fa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prescient</value>
      <webElementGuid>ee166f15-e14e-407c-a562-ad336bb77261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h&quot;]/header[@class=&quot;gap-20 relative md:fixed top-0 left-0 w-full bg-neutralsLightWhite z-50 items-stretch Page_pageheader__TBdOB&quot;]/div[@class=&quot;hidden sm:flex items-center&quot;]/h1[@class=&quot;type-14&quot;]/strong[1]</value>
      <webElementGuid>f124f440-c5e3-486b-9ee1-78eac3397c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/header/div/h1/strong</value>
      <webElementGuid>396817ab-005c-4ee0-a800-af6124da3846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to'])[1]/following::strong[1]</value>
      <webElementGuid>f3d70893-dea0-400a-b9f5-53eac69d5bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[1]/preceding::strong[1]</value>
      <webElementGuid>598be74c-e894-480a-8e54-0aecfdf67bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prescient']/parent::*</value>
      <webElementGuid>afa83431-c2f1-4ce5-ab2c-0c937c0343ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>fb223fb6-9679-4d46-b837-e02aa9f2cc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Prescient' or . = 'Prescient')]</value>
      <webElementGuid>ea433d0f-f3bb-422a-8b59-e618a59709a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
