<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Prescient Centralised Services (Pty) Lt_bd8bbf</name>
   <tag></tag>
   <elementGuidId>f5af7786-a6dd-402d-b8fa-f0ce2f154f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-0-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-0-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Prescient Centralised Services (Pty) Ltd (Prescient Umbrella Provident Fund) (PLUF00003#3) - Savings - Market Value R 53 759,08&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45696192-bf21-4b45-835d-310a2a769400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__option react-select__option--is-focused css-d7l1ni-option</value>
      <webElementGuid>e1e4a15f-5b72-4cef-ae02-bca983821039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11c2f7d3-e763-4c46-b3eb-39ce901336bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-0-1</value>
      <webElementGuid>06363a15-f547-4202-ba3e-5201796c68c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7f702362-bd26-4d88-9c68-7110b5978009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>222a7779-dcf7-4cc4-ac16-f6ed8b81eb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b21ae3cf-db45-4339-94bb-323733fe9d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prescient Centralised Services (Pty) Ltd (Prescient Umbrella Provident Fund) (PLUF00003#3) - Savings - Market Value R 53 759,08</value>
      <webElementGuid>6ea8acfe-4367-4687-bfeb-62da0c4d5247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-0-1&quot;)</value>
      <webElementGuid>c60a8742-3c2c-416c-9536-63374e1ce715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-0-1']</value>
      <webElementGuid>df596241-db33-4ed5-a97a-0982cc6e7c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div/div[2]/div[2]</value>
      <webElementGuid>bba860b4-162f-425e-9c02-c8fa870a4366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Benefit'])[1]/following::div[3]</value>
      <webElementGuid>86223149-63f5-40d6-9c68-770a5126985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Investment'])[1]/following::div[15]</value>
      <webElementGuid>052cd5ab-5ff8-4c1d-8350-b34b4da1b09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retirement Annuity'])[1]/preceding::div[3]</value>
      <webElementGuid>0ced0120-c387-43af-b4b4-211458b1ee60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prescient Retirement Annuity Fund (PRA00194#3) - Savings - Market Value R 5 264,63'])[1]/preceding::div[4]</value>
      <webElementGuid>ff11a28b-76c3-4c05-a232-07821acd8a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>d407bca8-5e16-498d-997a-375288be8f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-0-1' and (text() = 'Prescient Centralised Services (Pty) Ltd (Prescient Umbrella Provident Fund) (PLUF00003#3) - Savings - Market Value R 53 759,08' or . = 'Prescient Centralised Services (Pty) Ltd (Prescient Umbrella Provident Fund) (PLUF00003#3) - Savings - Market Value R 53 759,08')]</value>
      <webElementGuid>d03580bf-5bd1-49d4-9c08-ca2e6106799e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
