<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NamePrescient</name>
   <tag></tag>
   <elementGuidId>5737428b-e35d-4abf-8e89-4466fe05972d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div[2]/section/section/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.LinkedInvestmentActionRow_name__6WDjF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;NamePrescient&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5877a75-7192-40a3-9714-bf2e626d0dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LinkedInvestmentActionRow_name__6WDjF</value>
      <webElementGuid>de023742-c7b6-4e17-9fd5-83dd05c92d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NamePrescient</value>
      <webElementGuid>4da2f16b-7354-4e9a-95fa-d3e5c5ae5ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;Page_page__6zv7h LinkedInvestments_linkedinvestments__8JL8W&quot;]/main[@class=&quot;Page_main__TY1Ck&quot;]/div[@class=&quot;max-w-wide&quot;]/div[@class=&quot;px-24 md:px-40 gapped-40 md:gapped-xl&quot;]/section[@class=&quot;grid gap-40 md:grid-cols-3&quot;]/section[@class=&quot;col-span-3 sm:col-span-2 gapped-16 type-14&quot;]/div[@class=&quot;LinkedInvestments_linkedInvestmentContainer__vlfjq&quot;]/div[1]/div[@class=&quot;LinkedInvestmentActionRow_linkedinvestmentactionrow__TvA1P LinkedInvestmentActionRow_forcedlabels__evZyE&quot;]/span[@class=&quot;LinkedInvestmentActionRow_name__6WDjF&quot;]</value>
      <webElementGuid>05ced5ee-6465-4673-8870-936731e7db47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div[2]/section/section/div/div/div/span[2]</value>
      <webElementGuid>e18c2c51-30eb-46db-b222-f1586b8c9e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Id'])[1]/following::span[1]</value>
      <webElementGuid>14f18fa2-6d05-418a-a189-ef6d64b1a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linked Investment Status'])[1]/following::span[3]</value>
      <webElementGuid>a410ee4e-9fc2-41c1-bbb5-8ebd00c1078d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>df6590f9-0fc7-4b38-84a3-bcdafb6ef90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NamePrescient' or . = 'NamePrescient')]</value>
      <webElementGuid>69e8118a-c44d-4498-a8eb-a89b1f95f971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
